version: "2"

services:
    frontend:
        build: ./sofraco-front-end
        restart: always
        ports:
            - "3000:3000"
        links:
            - backend
        networks:
            - netbridges
    backend:
        build: ./sofraco-back-end
        restart: always
        ports:
            - "9000:9000"
        depends_on:
            - mongodb-sofraco
        environment:
            MONGO_URL: mongodb://mongodb-sofraco:27017/sofraco
        networks:
            - netbridges

    mongodb-sofraco:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
#         ports:
#             - 27017:27017
        command: mongod --noauth
        networks:
            - netbridges

networks:
    netbridges:
        driver: bridge
