version: "2"

services:
    frontend:
        build: ./sofraco-front-end
        restart: always
        ports:
            - "3000:3000"
        links:
            - backend
        volumes:
            - ./sofraco-front-end:/fontend
        networks:
            - sofraco-network
    backend:
        build: ./sofraco-back-end
        restart: always
        ports:
            - "9000:9000"
        depends_on:
            - mongodb-sofraco
        environment:
            MONGO_URL: mongodb://mongodb-sofraco:27017/sofraco
        volumes:
            - ./sofraco-back-end:/backend
        networks:
            - sofraco-network

    mongodb-sofraco:
        image: mongo:5.0.3
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        command: mongod --noauth
        networks:
            - sofraco-network

networks:
    sofraco-network:
        driver: bridge
           

