name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST2 }}
        USERNAME: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT2 }}
        KEY: ${{ secrets.KEY }}
        command_timeout: 30m
        script: |
          cd Sofraco/
          git pull
          docker-compose build --no-cache
          docker-compose up -d
          docker image prune -f
