name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents to server via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
      with:
        source: "."
        target: "~/Sofraco"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        script: |
          cd Sofraco
          docker-compose up -d
